# Generated by Django 5.0 on 2023-12-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADS_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comparison_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('cus_user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Financial_Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FM_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('use_user_id', models.IntegerField()),
                ('discription', models.TextField()),
                ('method', models.CharField(max_length=100)),
                ('data_time', models.DateTimeField()),
                ('reference', models.CharField(max_length=100)),
                ('admin_configration', models.BooleanField()),
                ('im_port', models.DecimalField(decimal_places=2, max_digits=5)),
                ('export', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('notification_type', models.CharField(max_length=50)),
                ('notification_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photo_ADS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo_ADS_id', models.IntegerField()),
                ('photADS_id', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo_Property_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_Customer_id', models.IntegerField()),
                ('ADS_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('report_text', models.CharField(max_length=150)),
                ('report_type', models.CharField(max_length=100)),
                ('report_state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=25)),
                ('creat_date', models.DateField()),
                ('last_date', models.DateField()),
            ],
        ),
    ]
