# Generated by Django 5.0 on 2023-12-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_id', models.IntegerField()),
                ('City_id', models.IntegerField()),
                ('Area_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_id', models.ImageField(upload_to='')),
                ('Property_id', models.IntegerField()),
                ('User_ID', models.IntegerField()),
                ('Booking_Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chat_id', models.IntegerField()),
                ('User_ID', models.IntegerField()),
                ('Cus_user_id', models.IntegerField()),
                ('Chat1', models.TextField()),
                ('Chat2', models.TextField()),
                ('Date1', models.DateTimeField()),
                ('Date2', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_id', models.IntegerField()),
                ('City_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.IntegerField()),
                ('Area_id', models.IntegerField()),
                ('User_ID', models.IntegerField()),
                ('Order_Date', models.DateField()),
                ('Order_Type', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Start_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('End_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Room_Number', models.IntegerField()),
                ('Floor', models.CharField(max_length=100)),
                ('Details', models.TextField()),
                ('Build_Year', models.CharField(max_length=100)),
                ('Bathrooms', models.CharField(max_length=100)),
                ('Hall_Room', models.CharField(max_length=100)),
                ('Basement', models.CharField(max_length=100)),
                ('Pool', models.CharField(max_length=100)),
                ('Furnished', models.CharField(max_length=100)),
                ('Elevator', models.CharField(max_length=100)),
                ('Street_number', models.CharField(max_length=100)),
                ('Appendix', models.CharField(max_length=100)),
                ('Space', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_id', models.IntegerField()),
                ('Type_id', models.IntegerField()),
                ('Area_id', models.IntegerField()),
                ('User_ID', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('Features', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_Agent_id', models.IntegerField()),
                ('Order_id', models.IntegerField()),
                ('User_ID', models.IntegerField()),
                ('Report_Type', models.CharField(max_length=100)),
                ('Report_Text', models.CharField(max_length=100)),
                ('Report_State', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_id', models.IntegerField()),
                ('Type_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
