# Generated by Django 5.0 on 2024-01-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_countect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countect',
            new_name='Contact',
        ),
    ]
