# Generated by Django 5.0 on 2023-12-25 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chatting', '0002_evaluation_report_customer_delete_area_and_more'),
        ('order', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_agent',
            old_name='Report_State',
            new_name='report_state',
        ),
        migrations.RenameField(
            model_name='report_agent',
            old_name='Report_Text',
            new_name='report_text',
        ),
        migrations.RenameField(
            model_name='report_agent',
            old_name='Report_Type',
            new_name='report_type',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='cus_user_id',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluation_id',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='report_agent',
            name='Order_id',
        ),
        migrations.RemoveField(
            model_name='report_agent',
            name='Report_Agent_id',
        ),
        migrations.RemoveField(
            model_name='report_agent',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='report_customer',
            name='ADS_id',
        ),
        migrations.RemoveField(
            model_name='report_customer',
            name='Report_Customer_id',
        ),
        migrations.RemoveField(
            model_name='report_customer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.agent'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='report_agent',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.agent'),
        ),
        migrations.AddField(
            model_name='report_agent',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.order'),
        ),
        migrations.AddField(
            model_name='report_customer',
            name='ads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.ads'),
        ),
        migrations.AddField(
            model_name='report_customer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer'),
        ),
    ]
