# Generated by Django 5.0 on 2024-01-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0005_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
