# Generated by Django 5.0 on 2024-01-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0006_alter_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='username',
        ),
    ]
