# Generated by Django 5.0 on 2024-02-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0010_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
