# Generated by Django 5.0 on 2024-06-05 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0016_alter_comment_agent_alter_comment_customer_message'),
        ('property', '0025_remove_comparison_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_customer',
            name='ads',
        ),
        migrations.AddField(
            model_name='report_customer',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.property'),
        ),
    ]
