# Generated by Django 5.0 on 2024-06-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0017_remove_report_customer_ads_report_customer_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_agent',
            name='report_text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='report_customer',
            name='report_state',
            field=models.CharField(max_length=100),
        ),
    ]
