# Generated by Django 5.0 on 2024-01-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, upload_to='agentPhoto/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='customerPhoto/%Y/%m/%d/'),
        ),
    ]
