# Generated by Django 5.0.1 on 2024-02-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agent_photo_customer_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='photo',
            new_name='profil_photo',
        ),
    ]
