# Generated by Django 5.0 on 2024-05-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_photo_agent_profil_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='state',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
