# Generated by Django 5.0 on 2024-05-11 22:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agent_state_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profil_photo',
            field=models.ImageField(blank=True, upload_to=accounts.models.filepath1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, upload_to=accounts.models.filepath1),
        ),
    ]
