# Generated by Django 5.0.1 on 2024-05-27 21:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_agent_profil_photo_alter_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profil_photo',
            field=models.ImageField(blank=True, default='uploads/avatar.png', upload_to=accounts.models.filepath1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='uploads/avatar.png', upload_to=accounts.models.filepath1),
        ),
    ]
