# Generated by Django 5.0 on 2024-06-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_agent_slug_customer_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='who_i',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نبذة عني :'),
        ),
    ]
