# Generated by Django 5.0.1 on 2024-06-10 00:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_agent_who_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profil_photo',
            field=models.ImageField(blank=True, upload_to=accounts.models.filepath1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, upload_to=accounts.models.filepath1),
        ),
    ]
