# Generated by Django 5.0 on 2023-12-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FM_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('use_user_id', models.IntegerField()),
                ('discription', models.TextField()),
                ('method', models.CharField(max_length=100)),
                ('data_time', models.DateTimeField()),
                ('reference', models.CharField(max_length=100)),
                ('admin_configration', models.BooleanField()),
                ('im_port', models.DecimalField(decimal_places=2, max_digits=5)),
                ('export', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('notification_type', models.CharField(max_length=50)),
                ('notification_text', models.CharField(max_length=50)),
            ],
        ),
    ]
