# Generated by Django 5.0.1 on 2024-06-03 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0002_alter_financial_movement_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial_movement',
            name='user',
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='data_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
