# Generated by Django 5.0.1 on 2024-06-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0003_remove_financial_movement_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_movement',
            name='admin_configration',
            field=models.BooleanField(null=True),
        ),
    ]
