# Generated by Django 5.0.1 on 2024-06-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0004_alter_financial_movement_admin_configration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_movement',
            name='discription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='export',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='im_port',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
