# Generated by Django 5.0.1 on 2024-06-03 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_agent_profil_photo_alter_customer_photo'),
        ('fm', '0005_alter_financial_movement_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_movement',
            name='admin_configration',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.agent'),
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='data_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='export',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='im_port',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
