# Generated by Django 5.0.1 on 2024-06-03 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0006_alter_financial_movement_admin_configration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial_movement',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='financial_movement',
            name='export',
        ),
        migrations.RemoveField(
            model_name='financial_movement',
            name='im_port',
        ),
        migrations.RemoveField(
            model_name='financial_movement',
            name='method',
        ),
    ]
