# Generated by Django 5.0.1 on 2024-06-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0007_remove_financial_movement_discription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financial_movement',
            options={'verbose_name': 'Financial Movement', 'verbose_name_plural': 'Financial Movements'},
        ),
        migrations.RenameField(
            model_name='financial_movement',
            old_name='data_time',
            new_name='date_time',
        ),
        migrations.AlterField(
            model_name='financial_movement',
            name='admin_configration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
