# Generated by Django 5.0 on 2024-06-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0010_remove_financial_movement_created_by'),
        ('order', '0014_alter_order_bathrooms_alter_order_floor_and_more'),
        ('property', '0025_remove_comparison_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_movement',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.order'),
        ),
        migrations.AddField(
            model_name='financial_movement',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.property'),
        ),
    ]
