# Generated by Django 5.0 on 2023-12-25 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Description',
            new_name='tescription',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='Type_Name',
            new_name='type_Name',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='ADS_id',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='Comparison_id',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='photo_ads',
            name='Photo_ADS_id',
        ),
        migrations.RemoveField(
            model_name='photo_ads',
            name='photADS_id',
        ),
        migrations.RemoveField(
            model_name='photo_property',
            name='Photo_Property_id',
        ),
        migrations.RemoveField(
            model_name='photo_property',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Area_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Property_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Type_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='type',
            name='Type_id',
        ),
        migrations.AddField(
            model_name='ads',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.agent'),
        ),
        migrations.AddField(
            model_name='ads',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.property'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.property'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.property'),
        ),
        migrations.AddField(
            model_name='photo_property',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.agent'),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.type'),
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.area'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.city'),
        ),
    ]
