# Generated by Django 5.0 on 2024-01-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_ads',
            name='path',
        ),
        migrations.RemoveField(
            model_name='photo_property',
            name='path',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type_Name',
        ),
        migrations.AddField(
            model_name='photo_ads',
            name='photo',
            field=models.ImageField(blank=True, upload_to='adsPhoto/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='photo_property',
            name='photo',
            field=models.ImageField(blank=True, upload_to='propertyPhoto/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
