# Generated by Django 5.0 on 2023-12-25 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_area_city_rename_price_property_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Features',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Location',
            new_name='location',
        ),
    ]
