# Generated by Django 5.0 on 2024-01-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_photo_ads_path_remove_photo_property_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='property_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
