# Generated by Django 5.0 on 2024-01-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_type_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='tescription',
            new_name='description',
        ),
    ]
