# Generated by Django 5.0.1 on 2024-01-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_rename_property_type_type_search_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='phohto',
            field=models.ImageField(blank=True, null=True, upload_to='city_photo'),
        ),
    ]
