# Generated by Django 5.0 on 2024-03-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_city_phohto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='features',
            new_name='house_type',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='type_name',
            new_name='kitchen',
        ),
        migrations.AddField(
            model_name='property',
            name='img',
            field=models.ImageField(blank=True, upload_to='propertyPhoto/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='modern',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='roof',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
