# Generated by Django 5.0 on 2024-04-26 16:42

import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.ImageField(blank=True, upload_to=property.models.filepath),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
