# Generated by Django 5.0 on 2024-05-11 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agent_state_customer_state'),
        ('property', '0012_remove_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='properties', to='accounts.agent'),
        ),
    ]
