# Generated by Django 5.0 on 2024-05-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_property_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
