# Generated by Django 5.0 on 2024-05-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_favorite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'banned'), (2, 'active')], default=0),
        ),
    ]
