# Generated by Django 5.0 on 2024-05-30 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_area_area_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(choices=[('الوحدة', 'الوحدة'), ('صنعاء القديمة', 'صنعاء القديمة'), ('شعوب', 'شعوب'), ('أزال', 'أزال'), ('الصافية', 'الصافية'), ('السبعين', 'السبعين'), ('التحرير', 'التحرير'), ('معين', 'معين'), ('الثورة', 'الثورة'), ('بني الحارث', 'بني الحارث'), ('الحوبان', 'الحوبان')], max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='areas', to='property.city'),
        ),
    ]
