# Generated by Django 5.0 on 2024-06-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_alter_area_area_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='hall_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='house_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
