# Generated by Django 5.0 on 2024-06-01 16:58

import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_alter_property_bathrooms_alter_property_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_property',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photo_property',
            name='photo',
            field=models.FileField(blank=True, upload_to=property.models.filepath),
        ),
    ]
