# Generated by Django 5.0 on 2024-06-01 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_alter_photo_property_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_property',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='property.property'),
        ),
    ]
