# Generated by Django 5.0 on 2024-06-03 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_agent_profil_photo_alter_customer_photo'),
        ('property', '0023_alter_photo_property_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer'),
        ),
    ]
