# Generated by Django 5.0 on 2024-06-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_comparison_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='description',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='location',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='price',
        ),
    ]
