# Generated by Django 5.0.1 on 2024-06-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_remove_comparison_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.BooleanField(choices=[(0, 'inactive'), (1, 'banned'), (2, 'active')], default=0),
        ),
    ]
