# Generated by Django 5.0 on 2023-12-29 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.BooleanField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_number', models.IntegerField()),
                ('floor', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('build_year', models.CharField(max_length=100)),
                ('bathrooms', models.CharField(max_length=100)),
                ('hall_room', models.CharField(max_length=100)),
                ('basement', models.CharField(max_length=100)),
                ('pool', models.CharField(max_length=100)),
                ('furnished', models.CharField(max_length=100)),
                ('elevator', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=100)),
                ('appendix', models.CharField(max_length=100)),
                ('space', models.IntegerField(null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.area')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer')),
            ],
        ),
    ]
