# Generated by Django 5.0 on 2023-12-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_id', models.IntegerField()),
                ('City_id', models.IntegerField()),
                ('Area_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_id', models.ImageField(upload_to='')),
                ('Property_id', models.IntegerField()),
                ('User_ID', models.IntegerField()),
                ('Booking_Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_id', models.IntegerField()),
                ('City_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_id', models.IntegerField()),
                ('User_ID', models.IntegerField()),
                ('Order_Date', models.DateField()),
                ('Order_Type', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Start_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('End_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Room_Number', models.IntegerField()),
                ('Floor', models.CharField(max_length=100)),
                ('Details', models.TextField()),
                ('Build_Year', models.CharField(max_length=100)),
                ('Bathrooms', models.CharField(max_length=100)),
                ('Hall_Room', models.CharField(max_length=100)),
                ('Basement', models.CharField(max_length=100)),
                ('Pool', models.CharField(max_length=100)),
                ('Furnished', models.CharField(max_length=100)),
                ('Elevator', models.CharField(max_length=100)),
                ('Street_number', models.CharField(max_length=100)),
                ('Appendix', models.CharField(max_length=100)),
                ('Space', models.IntegerField()),
            ],
        ),
    ]
