# Generated by Django 5.0 on 2023-12-25 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('order', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Booking_Status',
            new_name='booking_status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Appendix',
            new_name='appendix',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Basement',
            new_name='basement',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Bathrooms',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Build_Year',
            new_name='build_year',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Elevator',
            new_name='elevator',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='End_Price',
            new_name='end_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Floor',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Furnished',
            new_name='furnished',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Hall_Room',
            new_name='hall_room',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Order_Date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Order_Type',
            new_name='order_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Pool',
            new_name='pool',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Area_id',
            new_name='space',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Start_Price',
            new_name='start_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Street_number',
            new_name='street_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Booking_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Property_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Space',
        ),
        migrations.RemoveField(
            model_name='order',
            name='User_ID',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.property'),
        ),
    ]
