# Generated by Django 5.0 on 2023-12-25 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('order', '0002_delete_area_delete_city_and_more'),
        ('property', '0002_area_city_rename_price_property_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.area'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer'),
        ),
    ]
