# Generated by Django 5.0 on 2023-12-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_booking_customer_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
