# Generated by Django 5.0 on 2023-12-25 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_area_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Room_Number',
            new_name='room_number',
        ),
    ]
