# Generated by Django 5.0 on 2023-12-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_room_number_order_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='space',
        ),
    ]
