# Generated by Django 5.0 on 2024-02-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_location_alter_order_appendix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='floor_room',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='housetype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='modern',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='roof',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
