# Generated by Django 5.0 on 2024-02-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_floor_room_order_housetype_order_kitchen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appendix',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='basement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='modern',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='roof',
            field=models.BooleanField(default=False),
        ),
    ]
