# Generated by Django 5.0 on 2024-02-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_appendix_alter_order_basement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
