# Generated by Django 5.0 on 2023-12-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='space',
        ),
    ]
