# Generated by Django 5.0 on 2024-02-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_price',
            field=models.IntegerField(null=True),
        ),
    ]
