# Generated by Django 5.0 on 2023-12-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='space',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
