# Generated by Django 5.0 on 2024-04-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_appendix_alter_order_basement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='floor_room',
        ),
    ]
