# Generated by Django 5.0 on 2024-05-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_floor_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
